pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        // ✅ Repositorio oficial de Arthenica para ffmpeg-kit
        maven { url 'https://arthenica.com/maven' }
    }
}

rootProject.name = "ProEditor"
include ':app'
